config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :comments, only: [:create]
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "home#index"
  get '/posts', to: 'posts#index', as: 'user_root'
  post '/new_user_reaction', to: 'reactions#new_user_reaction', as:
  'new_user_reaction'
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :reactions, dependent: :destroy

    Kinds = %w[like dislike].freeze
    KindsSpanish = {"like" => "Me gusta", "dislike" => "No me gusta"}.freeze

    has_one_attached :image

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action only: [:new, :create] do
    authorize_request(["author","admin"])
  end

  before_action only: [:edit, :update, :destroy] do
    authorize_request(["author","admin"])
  end

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comment = Comment.new
    @comments = @post.comments
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.required(:post).permit(:title, :image, :description, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class = 'mb-3'>
    <%= form.label :title, 'Titulo', style: "display: block", class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class = 'mb-3'>
    <%= form.label :image, 'Imagen', style: "display: block", class: 'form-label' %>
    <%= form.file_field :image, class: 'form-control' %>
  </div>

  <div class = 'mb-3'>
    <%= form.label :description, 'Descripcion', style: "display: block", class: 'form-label' %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class = 'mb-3'>
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class = 'mb-3'>
    <%= form.submit 'Publicar', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= post.image %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= post.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= post.user.email %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editar publicacion</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Ver publicacion", @post, class: 'btn btn-success' %> |
  <%= link_to "Volver a publicaciones", posts_path, class: 'btn btn-secondary' %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Publicaciones</h1>

<div class="mb-3">
  <%= link_to "Nueva publicacion", new_post_path, class: 'btn btn-primary' %>
</div>
<div id="posts" class="mb-3">
  <% @posts.each do |post| %>
    <div class="card" style="width: flex; margin-top: auto; margin-bottom: 10px">
      <div class="card-header">
          <h6 class="card-subtitle mb-2 text-body-secondary"><%= post.user.email %></h6>
      </div>
      <div class="card-body">
        <h5 class="card-title"><%= post.title %></h5>
        <p><%= image_tag(post.image, class: 'img-fluid') %></p>
        <p class="card-text"><%= post.description %></p>
        <%= link_to "Mostrar", post, class: 'btn btn-success' %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>Nueva publicacion</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Volver", posts_path, class: 'btn btn-secondary' %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<div class = "mb-3">
  <%= link_to "Volver", posts_path, class: 'btn btn-secondary' %>
</div>

<div class="card" style="width: flex;">
  <div class="card-header">
      <h6 class="card-subtitle mb-2 text-body-secondary"><%= @post.user.email %></h6>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= @post.title %></h5>
    <p><%= image_tag(@post.image, class: 'img-fluid') %></p>
    <p class="card-text"><%= @post.description %></p>
    <% if user_signed_in? %>
      <div class = "d-flex justify-content-between">
        <div class = "d-flex justify-content-start">
          <% if current_user.id == @post.user.id %>
            <%= link_to "Editar", edit_post_path(@post), class: 'btn btn-info', style: 'margin: 5px;' %>
            <%= button_to "Eliminar", @post, method: :delete, class: 'btn btn-danger', style: 'margin: 5px;' %>
          <% end %>
        </div>
        <div class = "d-flex justify-content-end">
          <% Post::Kinds.each do |kind| %>
            <% if kind == 'like' %>
              <%= button_to "#{Post::KindsSpanish[kind]} <i class='fas fa-thumbs-up'></i>".html_safe, new_user_reaction_path(post_id: @post.id, reaction_type: "post", kind: kind), method: :post, class: 'btn btn-primary', style: 'margin: 5px;' %>
            <% else kind == 'dislike' %>
              <%= button_to "#{Post::KindsSpanish[kind]} <i class='fas fa-thumbs-down'></i>".html_safe, new_user_reaction_path(post_id: @post.id, reaction_type: "post", kind: kind), method: :post, class: 'btn btn-danger', style: 'margin: 5px;' %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="card" style="margin-top: 10px;">
  <div class="card-body">
    <h2>Comentarios</h2>
    <%= render 'comments/form' %>
  </div>
</div>

<div style="margin-top: auto; margin-bottom: 10px">
  <% @comments.each do |comment| %>
    <div class="card" style="width: flex; margin-top: 10px;">
      <div class="card-body">
        <% if comment.user.nil? %>
          <h6 class="card-title">Escrito por: Anónimo</h6>
        <% else %>
          <h6 class="card-title">Escrito por: <%= comment.user.email %></h6>
        <% end %>
        <p class="card-text"><%= comment.content %></p>
      </div>
    </div>
  <% end %>
</div>